<?php

namespace DemandeBundle\Repository;
use DemandeBundle\Entity\Demande;

use Doctrine\ORM\EntityRepository;

/**
 * ModeleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DemandeRepository extends \Doctrine\ORM\EntityRepository
{


    public function myfindall($prixmin,$prixmax){
        $query=$this->getEntityManager()
            ->createQuery("select * from DemandeBundle:Demande m where m.prix between '$prixmin' and '$prixmax' ");
        return $query->getResult();
    }
}
