offre_homepage:
    path:     /
    defaults: { _controller: OffreBundle:Default:index }

offre_affiche:
    path:     /affiche
    defaults: { _controller: OffreBundle:Offre:affiche }

offre_show:
    path:     /{id}/show
    defaults: { _controller: OffreBundle:Offre:show }

offre_mesoffres:
    path:     /mesoffres
    defaults: { _controller: OffreBundle:Offre:mesoffres }

offre_postuler:
    path:     /{id}/postuler
    defaults: { _controller: OffreBundle:Offre:postuler }

offre_delete:
    path:     /delete/{id}
    defaults: { _controller: OffreBundle:Offre:delete }
