offre_homepage:
    path:     /
    defaults: { _controller: OffreBundle:Default:index }

affiche:
    path:     /affiche
    defaults: { _controller: OffreBundle:Offre:affiche }

show:
    path:     /show
    defaults: { _controller: OffreBundle:Offre:show }

mesprojets:
    path:     /mesprojets
    defaults: { _controller: OffreBundle:Offre:mesprojets }

postuler:
    path:     /postuler
    defaults: { _controller: OffreBundle:Offre:postuler }

delete:
    path:     /delete
    defaults: { _controller: OffreBundle:Offre:delete }
